### ISSUE TITLE
Fuck or Fucking?

### ISSUE THREAD

**Issue by hyrmn** [hyrmn/everyfuckingnoun#5]
What's funnier?

Fuck Capitalism  
Fucking Capitalism

Fuck Gumminess 
Fucking Gumminess

**Comment by jglinsek** [comment]
Count me in for "Fucking".

**Comment by hyrmn** [comment]
> 
> 
> Count me in for "Fucking".

Resolved and pushed.
https://github.com/hyrmn/everyfuckingnoun/commit/aeb2845167fc5a3d812353e104d27c6c1d81e543
